### ISSUE TITLE
HAVING clause does not read AS columns?

### ISSUE THREAD

**Issue by monetdb-team** [MonetDB/MonetDB#3780]
Date: 2015-08-08 04:22:55 +0200
From: Anthony Damico &lt;<ajdamico>&gt;
To:   SQL devs &lt;<bugs-sql>&gt;
Version: -- development
CC:   ajdamico, martin.van.dinther, @njnes, till.wollenberg

Last updated: 2019-01-14 13:35:16 +0100

## Comment 21104
Date: 2015-08-08 04:22:55 +0200
From: Anthony Damico &lt;<ajdamico>&gt;

User-Agent:       Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
 Build Identifier: 
 
 sorry if i'm mistaking the usage of HAVING, but this works in SQLite so i'm confused why it's breaking in monetdb?
 
 Reproducible: Always
 
 ### Steps to Reproduce:
 CREATE TABLE bugexample (id INTEGER , value INTEGER);
 INSERT INTO bugexample VALUES ( 1 , 1 ) , ( 2 , 2 ) , ( 2 , 2 ) ;
 
 SELECT id FROM bugexample GROUP BY id HAVING id > 1;
 SELECT id , SUM( value ) AS z FROM bugexample GROUP BY id HAVING z > 1;
 SELECT id , COUNT(*) AS z FROM bugexample GROUP BY id HAVING z > 1;
 
 ### Actual Results:  
 sql>CREATE TABLE bugexample (id INTEGER , value INTEGER);
 operation successful (12.075ms)
 sql>INSERT INTO bugexample VALUES ( 1 , 1 ) , ( 2 , 2 ) , ( 2 , 2 ) ;
 3 affected rows (5.528ms)
 sql>
 sql>SELECT id FROM bugexample GROUP BY id HAVING id > 1;
 +------+
 | id   |
 +======+
 |    2 |
 +------+
 1 tuple (0.941ms)
 sql>SELECT id , SUM( value ) AS z FROM bugexample GROUP BY id HAVING z > 1;
 SELECT: identifier 'z' unknown
 sql>SELECT id , COUNT(*) AS z FROM bugexample GROUP BY id HAVING z > 1;
 SELECT: identifier 'z' unknown
 sql>
 
 ### Expected Results:  
 read the dynamically-created column

## Comment 21108
Date: 2015-08-08 17:08:20 +0200
From: @njnes

the having is handled before the selection, ie the z alias isn't known jet.

## Comment 21109
Date: 2015-08-08 17:10:33 +0200
From: Anthony Damico &lt;<ajdamico>&gt;

sorry, i'm confused, how should this query be written?

## Comment 21112
Date: 2015-08-08 17:26:37 +0200
From: Anthony Damico &lt;<ajdamico>&gt;

hi, these queries work as a workaround, but i thought the whole point of HAVING was to filter a query *after* it had been generated?
 
 SELECT z , id FROM ( SELECT id , SUM( value ) AS z FROM bugexample GROUP BY id ) AS w GROUP BY id , z HAVING z > 1;
 
 SELECT z , id FROM ( SELECT id , COUNT(*) AS z FROM bugexample GROUP BY id ) AS w GROUP BY id , z HAVING z > 1;
 
 
 the GROUP BY is necessary for the HAVING statement (so these commands do not work)..  i don't understand the utility of HAVING if it cannot read an alias?
 
 SELECT * FROM ( SELECT id , SUM( value ) AS z FROM bugexample GROUP BY id ) AS w HAVING z > 1;
 
 SELECT * FROM ( SELECT id , COUNT(*) AS z FROM bugexample GROUP BY id ) AS w HAVING z > 1;

## Comment 21140
Date: 2015-08-13 15:39:57 +0200
From: Martin van Dinther &lt;<martin.van.dinther>&gt;

I think you are right in that the alias name should be usable in the HAVING clause, so I reopened this issue.
 
 For the time being some possible workarounds are:
 1) duplicate the aggregate-expression in the HAVING clause like:
 SELECT id , SUM( value ) AS z FROM bugexample GROUP BY id HAVING SUM(value) > 1;
 SELECT id , COUNT(*) AS z FROM bugexample GROUP BY id HAVING COUNT(*) > 1;
 
 2) use aggregate query in the FROM-clause like:
 SELECT z , id FROM ( SELECT id , SUM( value ) AS z FROM bugexample GROUP BY id ) AS w WHERE z > 1;
 SELECT z , id FROM ( SELECT id , COUNT(*) AS z FROM bugexample GROUP BY id ) AS w WHERE z > 1;
 These are a little different from your workarounds, as you do not need to GROUP twice.
 
 3) use WITH-clause like:
 WITH w as (SELECT id , SUM( value ) AS z FROM bugexample GROUP BY id) SELECT z , id FROM w  WHERE z > 1;
 WITH w as (SELECT id , COUNT(*) AS z FROM bugexample GROUP BY id) SELECT z , id FROM w  WHERE z > 1;
 
 4) create an aggregation VIEW once like:
 CREATE VIEW w AS SELECT id, COUNT(*) AS count, SUM(value) AS sum_value FROM bugexample GROUP BY id;
 and next use that view  for all queries on the aggregate:
 SELECT sum_value, id FROM w  WHERE sum_value > 1;
 SELECT count, id FROM w  WHERE count > 1;
 
 Thanks for reporting this issue/request.

**Comment by eyalroz** [comment]
I'd also very much like to see this implemented. Would reduce a significant incompatibility with other DBMS which requires adaptation (not to mention that it's been part of the SQL standard since forever, IIANM).

**Comment by eyalroz** [comment]
Also, the title should be renamed, to "Apply HAVING on aggregate columns, as per SQL standard". The whole [point of `HAVING`](https://en.wikipedia.org/wiki/Having_(SQL)) is to apply to aggregates and otherwise SELECT'ed columns - unlike `WHERE`.

**Comment by swingbit** [comment]
@eyalroz , although I would also like aliases to be usable in `HAVING` clauses, the Wikipedia link you posted does not really make a point. In fact, it shows the opposite: `HAVING` clauses not using aliases, `WHERE` clauses using them (from a sub-select).

Also, please someone correct me if I'm wrong, but I believe the SQL standard _does not_ specify that aliases defined in the `SELECT` clause can be used in the `HAVING` clause.
A select query is evaluated, _conceptually_, in the following order:

1. The `from` clause
2. The `where` clause
3. The `group by` clause
4. The `having` clause
5. The `select` clause
6. The `order by` clause

Which means, the `ORDER BY` clause is the only one that can use aliases defined in the `SELECT`. Not even the `WHERE` clause can use them. They can only use columns coming from the `FROM` clause. So in in order to use them, you would have to resort to a sub-select.

That said, this is how it works conceptually. Most DBMS vendors allow a different evaluation order and do allow to use said aliases in all clauses. In MonetDB, only `HAVING` does not allow that, and I agree it would be nice if it did. But these are choices that are up to the implementation and the argument of "as per SQL standard" is not valid, I think.

**Comment by eyalroz** [comment]
@swingbit : I might be wrong on the evaluation order. In that case - I take back my last comment - but would still like the aliases to be usable in `HAVING`.
