### ISSUE TITLE
Website's search results have wrong domain

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7072]
**Describe the bug**
On www.monetdb.org, the integrated search produces results whose links have `localhost:8080` as domain.

**To Reproduce**
Try e.g. https://www.monetdb.org/search/node?keys=stethoscope and check any result link.

BTW, mind the typo here:

```
Create a setting with minimal input for an external user to demonstrate him the buggy behavior.
This includes the relevant part of the database  schema description.
Performance trace of the roque query (using the TRACE command)
                         ^^^^^
```

**Comment by yzchang** [comment]
Thanks for pointing this out.  This problem appeared recently.  We've been searching everywhere for its cause and a solution.  Unfortunately, so far, no success.

Replacing the `localhost:8080` part in the broken URLs with `monetdb.org` is a workaround.

**Comment by njnes** [comment]
Some fixes were added too the proxy server for this, ie seems too work again.

**Comment by swingbit** [comment]
The issue is back

**Comment by sjoerdmullender** [comment]
It seems to have repaired itself.

**Comment by yzchang** [comment]
It's happening again.

**Comment by kutsurak** [comment]
Sjoerd, noticed that this happens after rebooting the host, but the problems goes away if one of the services is restarted. We changed the configuration so that service is started last after a reboot, and this seems to have worked after a test reboot.

We will be keeping an eye on this, but do let us know if the problem reappears.
