### ISSUE TITLE
pystethoscope example lacks explanation + doesn't properly work

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7100]
[This page](https://www.monetdb.org/blog/pystethoscope) describes the new pystethoscope tool.

It gives an example of how to use it: If you issue:
```
pystethoscope -i pc,usec,state,stmt  -t statement -e version sf10 
```
then supposedly you would get useful progress info. However:

* It doesn't say _what_ information will be printed.
* It doesn't say what switches are being used
* It doesn't explicitly say what database is being connected to
* It doesn't say what resolution of information we would get
* The sample output is a raster image, which on a decent display, looks like ant trails, not any sort of text.
* ... and if that's not problematic enough, the syntax is wrong. You specify the DB name with `-d` with the current version of pysthethoscope :-(

When I fix the syntax, it's accepted, but what I get is:
```
 pystethoscope -d ontime5 -i pc,usec,state,stmt  -t statement -e version
Connected to the database: ontime5
Key pc,usec,state,stmt not found in the JSON object
{}
Key pc,usec,state,stmt not found in the JSON object
{}
Key pc,usec,state,stmt not found in the JSON object
{}
Key pc,usec,state,stmt not found in the JSON object
{}
Key pc,usec,state,stmt not found in the JSON object
{}
Key pc,usec,state,stmt not found in the JSON object
{}
```
(and a few more of those lines.)

**Comment by kutsurak** [comment]
Hi Eyal!

Take a look at the [documentation](https://monetdb-pystethoscope.readthedocs.io/en/latest/) of the tool itself, and specifically the high level [introduction](https://monetdb-pystethoscope.readthedocs.io/en/latest/introduction.html), the more detailed [usage reference](https://monetdb-pystethoscope.readthedocs.io/en/latest/usage.html), and the profiler [JSON format](https://monetdb-pystethoscope.readthedocs.io/en/latest/mal_reference.html). It's been some time since I tended to the documentation, but it should be reasonably up to date. If you find discrepancies let us know at the project's [repo](https://github.com/MonetDBSolutions/monetdb-pystethoscope).

**Comment by eyalroz** [comment]
@kutsurak : Hi Panos :-)

The documentation is better, but - that's not something you find when you look for stethoscope or pystethoscope on the MonetDB website:

* https://www.monetdb.org/search/node?keys=pystethoscope
* https://www.monetdb.org/search/node?keys=stethoscope

At least add a comment to that blog post saying the syntax is out of date and offer a link to the documentation. Will check for any discrepancies later on.

**Comment by kutsurak** [comment]
heh, the blog post was current when it was written and the documentation probably was not there yet ;-)

I agree, though, it should contain a link to the documentation and the repository itself.
