### ISSUE TITLE
DB stop problems with a long-running query

### ISSUE THREAD

**Issue by eyalroz** [MonetDB/MonetDB#7124]
This continues the scenario in #7123 .

Suppose you have a long-running query (SELECT only, no changes to the data), which you stop from another connection with `call sys.stop(the_tag_id)`. You wait a few minutes, then terminate the (first) connection with Ctrl+C. You now issue `monetdb stop the_db_name`.

First, the DB takes much too long to stop. Since the query did not change any data, there's no RAM-resident data which needs to be written to disk, or any other significant housekeeping to do. Yet - it takes over 30 seconds on my system (Intel i7600k, 16GB memory, not otherwise heavily-loaded).

Second, the final result is a crash. That is, the `monetdb stop` command prints `done`, but then I get:
```
 name   state   health                 remarks
dbname  C  1d    9% 10s  crashed (started...1-05-08 23:12:42)
```
there shouldn't have been a crash.

**Software versions**
 - MonetDB 11.39.11
 - Devuan GNU/Linux Beowulf
 - Built from source

**Comment by yzchang** [comment]
Hai Eyal, all your problems with cancelling long-running queries doesn't seem to work are due to the current implementation: MonetDB only stops executing the cancelled query, after it has finished executing the current (MAL) instruction.  Many of your problems will be solved with the new query-cancelling implementation, in which, with a small performance cost, MonetDB checks if it should stop the query execution _within_ some long-running MAL instructions.  In this way, MonetDB can really cancel a query within seconds.  The new feature is expected in the feature release after Jul2021.

What happened here is most probably:
- mserver5 continued executing the long-running query after `monetdb stop <db>` was issued.  This is unrelated to if the query changes data or not.
- when the `monetdb stop` command timed out (afaik, default is 60 sec), the MonetDB daemon (`monetdbd`) issues a `kill -9` to stop this database the hard way. => this is noted as a crash.

**Comment by eyalroz** [comment]
I sort of suspected something like this was the case... 

Anyway, feel free to close this when those changes land.

**Comment by njnes** [comment]
what is the status of this problem on the current jul release?  and or on the current default, where additional query time outs are handled more gracefully.

**Comment by eyalroz** [comment]
@njnes : Hi Niels,

Unfortunately I don't quite have the time to look into this right now. I'm fine with closing the bug, and if I see this again in the future I'll reopen.

**Comment by PedroTadim** [comment]
I am going to close this for now
