### ISSUE TITLE
Alignment of global variables and predefined ones

### ISSUE THREAD

**Issue by ghost** [MonetDB/MonetDB#7164]
In the current version, it is not possible to introduce global variables, although some are defined implicitly in the code base.

It should be possible to introduce variables at the schema level again.
Furthermore, consider predefined variables, such as 'optimizer' to be turned into keyword with associated rule

SET OPTIMIZER 'minimal-path'

**Comment by PedroTadim** [comment]
Isn't this a duplicate of issue #7084 in a way?

**Comment by ghost** [comment]
yes, duplicate

**Comment by RayNeverLearns** [comment]
Was this ever solved? This issue was closed as was the one identified as a duplicate and I still get the same error "Variables cannot be declared on the global scope" in the latest version.

**Comment by njnes** [comment]
indeed both were close without reintroducing the ability for declaring  global variables.

**Comment by RayNeverLearns** [comment]
Got it. Meaning a decision was made not to implement this at all? Not in future versions, not ever? At least as far as it stands now.

**Comment by njnes** [comment]
The discussion was about how to get those variables behave conform the sql transactional semantics (isolation level and all). The conclusion was that it would be a lot of work and no (much) gain. Still ideas may change.

**Comment by RayNeverLearns** [comment]
I am not sure I am getting this correctly then, especially since you say it wouldn't be much gain. Something tells me I am not fully understanding what's being discussed here.

Say I am writing some script that involves a number of steps and some of those would require variables. From what little I understand (I am VERY new to MonetDB), there is no way to do this today other than creating a procedure for this script, even if it's not something you need saved or committed to the db, only to run it and drop it later. How is avoiding all this, which I feel is very common, almost no gain?

Unless, once again, I misunderstood what this issue described here is, but I am getting the same error message shown in the duplicate ticket #7084 when I try to declare them outside of a procedure: "Variables cannot be declared on the global scope."

**Comment by njnes** [comment]
If you'd implement a script in the database you indeed need to implement a procedure (or function). Both have local variables. Only if you intend to split the script into multiple calls, you need more global variables. And even those are private to your session. 
The current monetdb has persistent tables, global and local temporary tables and so called unlogged tables (later are shared by multiple sessions, but will be empty after server restart). I'm sure one of these could be a fallback for your script to store its temporary results in.
