### ISSUE TITLE
Issue while using Math functions with MonetDB v11.39.17 (Oct2020-SP5) ODBC Driver

### ISSUE THREAD

**Issue by sreejithssharma** [MonetDB/MonetDB#7166]
When we run any SQL with any math functions like SUM, AVG, etc, we are getting the below error from the driver.

**ExceptionLogger::GetExceptionMessage: Xerces exception caught XERCES_CPP_NAMESPACE::DOMException - can't supply error message**

**To Reproduce**
If we run the below pattern query, we find this issue.
SELECT SUM(DISTINCT <COLUMN_NAME>)  FROM "TABLE_NAME"  WHERE <COLUMN_NAME> = XXXXX;

**Expected behavior**
The query should execute fine and give the results of the sum of values from the column.

**Software versions**
 - MonetDB v11.39.17 (Oct2020-SP5)
 - CentOS 7
 - Compiled from Sources

**Issue labeling **
The issue with ODBC Driver came as bundled

One findings-

With the new driver, we see column names are as below... %15, %16 etc...

+---------------------+---------------------+---------------------+
| %15                 | %16                 | %17                 |
+---------------------+---------------------+---------------------+
| 126881638           | 126881812           | 126877634           |
+---------------------+---------------------+---------------------+

The same with old drivers, they are L3, L6, L11 etc... Will this cause anything specific to application we use?
+---------------------+---------------------+---------------------+
| L3                  | L6                  | L11                 |
+---------------------+---------------------+---------------------+
| 126881638           | 126881812           | 126877634           |
+---------------------+---------------------+---------------------+

**Comment by PedroTadim** [comment]
Hello! As the first debugging step, can you test the same setup using the recently released Jul2021 version? We fixed an issue related to distinct aggregates. Thanks!

**Comment by yzchang** [comment]
Concerning the error, with Oct2020-SP5, I got:
```
$ mclient -d demo
Welcome to mclient, the MonetDB/SQL interactive terminal (Oct2020-SP5)
Database: MonetDB v11.39.17 (Oct2020-SP5), 'mapi:monetdb://Styx.local:37199/demo'
FOLLOW US on https://twitter.com/MonetDB or https://github.com/MonetDB/MonetDB
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql> SELECT SUM(DISTINCT id) FROM sys.functions WHERE name = 'median';
+-------+
| %1    |
+=======+
| 90806 |
+-------+
```
The math functions seem to work for me.  Maybe this is an ODBC problem?
---
Concerning the auto-generated column names: since a recent MonetDB version (I can't quickly find the exact version number), we decided to no longer use the format 'L<N>' because the chance of conflicting with real column names is too large.  Since then, we've switched to the formal '%<N>'

**Comment by sjoerdmullender** [comment]
There is a known bug in the Oct2020-SP5 release in the ODBC driver.  It could be that you're affected by that.  In any case, using the top-of-tree version of the Oct2020 branch, I have no problem.
The bug is that the function SQLSpecialColumns is broken, so if your application uses that function to find out about columns, it will fail.

I just tried this (my ODBC setup is such that DSN=Oct2020 uses the Oct2020 branch, both server and ODBC driver) using Python and the pyodbc module:
>>> import pyodbc
>>> cnxn = pyodbc.connect('DSN=Oct2020')
>>> cursor = cnxn.cursor()
>>> cursor.execute("select sum(distinct id) from sys.functions where name = 'median'")
<pyodbc.Cursor object at 0x7ffb29c5fe30>
>>> cursor.fetchone()
(92066, )

**Comment by sreejithssharma** [comment]
Thanks all for the suggestions. I was able to get it work with latest version.
