### ISSUE TITLE
Do you have any plans to build the .deb packages of version 11.41.x for Ubuntu 1604?

### ISSUE THREAD

**Issue by xavierliu** [MonetDB/MonetDB#7183]
I noticed that there are not any .deb packages of version 11.41.x provided for Ubuntu 1604, I'd like to know do you have the plan for this? Or is there an instruction that describes how to build the .deb packages of version 11.41.x for Ubuntu 1604?

**Comment by kutsurak** [comment]
Ubuntu 16.04 has reached its "End of Standard Support" on April this year, and as such, MonetDB does not support it anymore. That is the reason why no .deb files are released for this particular distro anymore. The root problem is that old distributions contain old versions of libraries that may or may not be compatible with newer versions of MonetDB.

My advice is to upgrade to a more recent version of Ubuntu, but if you absolutely cannot do this for some reason, you can download the source code tarball from https://www.monetdb.org/downloads/sources/Latest/ and attempt to compile that. You can find instructions for how to do that in the [Readme](https://github.com/MonetDB/MonetDB#building) file of this repository.

**Comment by xavierliu** [comment]
@kutsurak, thanks for your explanation, looks like I can only compile it from source code.

**Comment by PedroTadim** [comment]
I am going to close this for now.

**Comment by xavierliu** [comment]
Hi @kutsurak, I try to build the deb packages using the following commands,

> mkdir build && cd build 
> cmake -DCMAKE_BUILD_TYPE=Release -DASSERT=OFF -DSTRICT=OFF /MonetDB/code/path 
> cmake --build . 
> cmake --build . --target create-deb-packages
> 

But the built deb packages cannot be installed successfully since the parameters "${shlibs:Depends}" and "${misc:Depends}" in the DEBIAN control file did not be replaced, I'm not familiar with building deb packages using cmake, could you please give me some advice? I'm so appreciated.

**Comment by xavierliu** [comment]
Hi @PedroTadim, could you please give me some advice? thanks.

**Comment by PedroTadim** [comment]
I don't build Debian related packages myself :) but @kutsurak can help you?

**Comment by xavierliu** [comment]
Hi @PedroTadim, thanks for your prompt reply, I'm looking forward to the advice from @kutsurak.

**Comment by kutsurak** [comment]
Hi @xavierliu. Sorry for the late answer! 

We do not use cmake to build .deb files for the platforms that we do publish .debs. We use a set of scripts that is not open source and I don't think that we intend to publish them. In my earlier reply, where I suggested that you use `cmake` I was referring to use that in order to build the executables directly, not .deb files.

For example the sequence:

```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local /path/to/monetdb/source
cmake --build .
sudo cmake --build . --target install
```

will compile and install the tools `mserver5`, `monetdbd`, `monetdb`, `mclient` (and a few others) as well as the needed libraries at `/usr/local` on the host. After that you can use these tools provided that `/usr/local/bin` is in your `PATH` variable. 

You should DEFINITELY remove older installations of MonetDB on the hosts that you are going to try this. 

Please keep in mind that recent versions of MonetDB have not been tested and do not officially support Ubuntu 16.04. You might encounter issues that we are not going to be able to help you with.

**Comment by kutsurak** [comment]
Sorry, the first `cmake` command in the previous comment should be:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local /path/to/monetdb/source
```

**Comment by xavierliu** [comment]
Hi @kutsurak, got it, thanks a lot.
