### ISSUE TITLE
The certificate has expired?

### ISSUE THREAD

**Issue by xavierliu** [MonetDB/MonetDB#7188]
Hi, when I installing the MonetDB on Ubuntu 1804 follow the instructions on [this page](https://www.monetdb.org/downloads/deb/), the error message shows that the certificate has expired,

> Err:10 https://dev.monetdb.org/downloads/deb bionic Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 192.16.197.137 443]
Reading package lists... Done
E: The repository 'https://dev.monetdb.org/downloads/deb bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Did I miss something?

**Comment by kutsurak** [comment]
I encountered a similar error recently. The root cause is that on October 1st one older Root Certificate that was used by Let's Encrypt expired (see [here](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) for details). The solution that worked for me on an Ubuntu 18.04 box was to upgrade the package `ca-certificates`:

```
sudo apt install ca-certificates
```

After this I was able to install MonetDB packages normally.
