### ISSUE TITLE
failed to start monetdb database on Android termux

### ISSUE THREAD

**Issue by l1t1** [MonetDB/MonetDB#7223]
I request a package on termux GitHub, and installed it successfully.  
then I followed the steps in https://cloud.tencent.com/developer/article/1054833
and failed at the step of  $ monetdb start my-first-db
see
https://github.com/termux/termux-packages/issues/8520

**Comment by yzchang** [comment]
Afais, you successfully installed monetdb, your problem is independent of the steps in the tencent article (a very nice one btw 👍). The merovingian.log says

```
failed to fork mserver: database 'my-first-db' appears to shut itself down after starting.
```

This usually indicates a crash during start up, and so far only happens with an existing database.  But your database was freshly created…

I wonder if this is because termux.  Afaik, we’ve never tried MonetDB on termux.

**Comment by l1t1** [comment]
thanks. 
very similar error at https://www.monetdb.org/pipermail/users-list/2012-September/005783.html
