### ISSUE TITLE
"hidden" underscores in docs

### ISSUE THREAD

**Issue by dancromartie** [MonetDB/MonetDB#7235]
I noticed this on the [serial types docs page](https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-types/serial-types/), but maybe it exists in additional places. I am pretty confused, as it doesn't seem pervasive.

I typed "AUTO INCREMENT" into a table creation statement, and Monet complained about my syntax. Eventually I copy-pasted the example from the docs, and saw that there is an underscore that is invisible to the eyes, but is in the source HTML. If it's just about font-color, it seems to be a very exact match, so that's interesting. This is happening in both the syntax explanation block, and at `CREATE TABLE test_serial`

Possibly related to browser (Firefox 96 on Ubuntu)

Screenshot below

![Screenshot from 2022-01-31 09-21-34](https://user-images.githubusercontent.com/8081676/151811919-160b3006-e359-4452-bf70-98476c6109f0.png)

**Comment by yzchang** [comment]
thanks for reporting, but this is very strange.

I checked the documentation source code, `AUTO_INCREMENT` is in the same code block as `text_serial`.  So that doesn't explain why the one is "hidden" while the other is not.  (However, `AUTO_INCREMENT` is the only capitalised word with an underscore on this page.  All other places where an underscore is used have lower-case letters.)

But I can't reproduce this problem on Firefox 96, Safari and Chrome (all on Mac OS).

**Comment by dancromartie** [comment]
Thanks - I pulled out my other computers and it also looked fine there. In any case, I think the issue may be related to the `line-height` property in the CSS for `<pre>` tags. It says `1.15` when I inspect it.

On Ubuntu Firefox, changing that to `1.16` and `1.18` keeps the underscore hidden, but using `1.17` or `1.19` and above makes it visible again. (Strange that there are gaps in this series)

On Firefox on my Mac, `line-height` of 1.02 and below will make it disappear. On my Mac's Safari, 1.06 is the magic cutoff.

I'm not a CSS expert so not sure who is "to blame" here, but that's what I'm seeing! Understandable if it's not worth changing anything for a low-prevalence issue.

**Comment by sjoerdmullender** [comment]
I have also "seen" the missing underscores.  After looking really hard, I did find them, but very unclear.  This was in firefox on linux.  On other browsers it was ok.

I reported this to our website guru, but I guess he hasn't been able yet to fix the issue.

**Comment by dancromartie** [comment]
Ah ok. Right, certain line heights seem to half-eat the underscore, so in some instances they may just appear very skinny.

**Comment by Giovanni-Valcarenghi** [comment]
I tried to solve it but I couldn't understand where was the problem mainly because I couldn't reproduce it. However, as you @dancromartie reported, it was a problem related to the `line-height` property for `<pre>` tags, that when too low there was eventually an overlapping of the lines (on some browsers). I have increased the default value, and now it should be fixed. Thanks for reporting.
