### ISSUE TITLE
Object not found

### ISSUE THREAD

**Issue by 847880028** [MonetDB/MonetDB#7260]
![image](https://user-images.githubusercontent.com/44664236/156286498-10eb8907-a3cf-4202-9aaa-a935b6700f36.png)
![image](https://user-images.githubusercontent.com/44664236/156286803-36909354-4f21-4157-b00e-0ab77e377b2d.png)
![image](https://user-images.githubusercontent.com/44664236/156286575-643ba07d-cd60-4b5f-9c5e-602cfa5c3fcf.png)
![image](https://user-images.githubusercontent.com/44664236/156286650-accc7416-179a-4561-bc8d-3c9bb880986d.png)
![image](https://user-images.githubusercontent.com/44664236/156286722-b0e6776f-cc5f-409e-a5d0-6d1b9208c454.png)
Check whether the virtual memory cannot be released
Check whether there are commands that can be restored

**Comment by 847880028** [comment]
![image](https://user-images.githubusercontent.com/44664236/156311491-cc8c4046-729d-49f7-b475-7536476226f3.png)
![image](https://user-images.githubusercontent.com/44664236/156311287-625c0de8-e058-4c9f-ac90-be79d6b88c7e.png)
![image](https://user-images.githubusercontent.com/44664236/156311392-3c9c4194-7c56-45d1-965f-494faa80d47a.png)
Memory doesn't change
cant login

**Comment by PedroTadim** [comment]
Can you tell which version of MonetDB you are using?

**Comment by 847880028** [comment]
![image](https://user-images.githubusercontent.com/44664236/156473941-23b178e5-5dc4-4ff1-bb4f-76dfd0b3ada8.png)

**Comment by 847880028** [comment]
There's no memory flushing mechanism or something? If the import operation fails, the memory will pile up and will not be cleared, resulting in subsequent operations will fail or even the thread will be closed by OOM killer.

**Comment by PedroTadim** [comment]
The memory used should be freed on error.

**Comment by mvdvm** [comment]
What happens if you restart the MonetDB server (so first stop and next start)?
Can you than run the SQL queries, or do they still create GDKmalloc errors?

For the COPY statements you may want to add the "n RECORDS" clause, see:
https://www.monetdb.org/documentation-Jan2022/user-guide/sql-manual/data-loading/copy-from/

Also please upgrade to the latest Jul2021 patch release:
https://www.monetdb.org/documentation-Jan2022/admin-guide/release-notes/jul2021/
or to the latest MonetDB release:
https://www.monetdb.org/documentation-Jan2022/admin-guide/release-notes/jan2022/
