### ISSUE TITLE
webdocumentation: Add borders to cells for information presented as table for improved readability

### ISSUE THREAD

**Issue by mvdvm** [MonetDB/MonetDB#7283]
**Describe the bug**
Currently some web information presented as tables do not show a 1px border around the cells. It would greatly enhance the readability of the tabular information if a small grey cell border is shown (like on the old website).
For instance the tabular documentation on supported scalar functions, procedures, sql-catalog, ... would need borders:

**To Reproduce**
See webpages:
https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/mathematics-functions/
https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/string-functions/
https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/logical-functions/
https://www.monetdb.org/documentation-Jan2022/user-guide/sql-functions/comparison-functions/
etc. 
https://www.monetdb.org/documentation-Jan2022/admin-guide/monitoring/session-procedures/
https://www.monetdb.org/documentation-Jan2022/admin-guide/monitoring/system-procedures/
etc. 
https://www.monetdb.org/documentation-Jan2022/user-guide/sql-catalog/schema-table-columns/
https://www.monetdb.org/documentation-Jan2022/user-guide/sql-catalog/functions-arguments-types/
etc. 

versus the original webpages with borders:
http://web.archive.org/web/20210412214522/https://www.monetdb.org/Documentation/SQLReference/FunctionsAndOperators/MathematicalFunctionsOperators
http://web.archive.org/web/20210513030115/https://monetdb.org/Documentation/SQLReference/SystemProcedures

The old ones are much easier to read and understand, due to the visual assistance of the borders around the cells of the tables.

**Expected behavior**
Show black/grey borders (1px) around every cell of tabular presented information.
Also the header (top row) with the field names, should have a different background than the information rows.

**Software versions**
www.monetdb.org website pages

**Additional context**
Other RDBMS documentation websites also use borders around cells of tabular presented information.
See for instance:
https://dev.mysql.com/doc/refman/8.0/en/built-in-function-reference.html
https://www.postgresql.org/docs/current/functions-math.html
https://mariadb.com/kb/en/function-and-operator-reference/

**Comment by joerivanruth** [comment]
I believe most of the tables you refer to should not be tables in the first place. The descriptions of the various functions and procedures should be description lists or something similar. 
For the remainder, it would probably be sufficient to set the vertical cell alignment to top instead of center, so you get
```
column 1    column 2    a very long
                        message with
                        line breaks
```
instead of
```
                        a very long
column 1    column 2    message with
                        line breaks
```

If you would like some help mass converting the tables, let me know

**Comment by Giovanni-Valcarenghi** [comment]
I have inserted a new shortcode inside the Hugo logic and now we can style the markdown tables in different ways. In order to style an MD table with the new documentation layout, you have to embed the table within those tags `{{<table "CSS-classes">}} md_table {{</table>}}`, doing so Hugo will apply the CSS-classes to the MD table during the generation of the website. Up to now, we have two CSS classes to style the tables: `table-bordered` which insert a thin border to the table, and `table-striped` which colors the tables with stripes (you can also use them in combination).

**Comment by Giovanni-Valcarenghi** [comment]
I have inserted a new shortcode inside the Hugo logic and now we can style the markdown tables in different ways. In order to style an MD table with the new documentation layout, you have to embed the table within those tags `{{<table "CSS-classes">}} md_table {{</table>}}`, doing so Hugo will apply the CSS-classes to the MD table during the rendering of the website. Up to now, we have two CSS classes to style the tables: `table-bordered` which inserts a thin border to the table, and `table-striped` which colours the tables with stripes (you can also use them together). 
An example of a table with borders (ofc here it won't be displayed):
```
{{<table "table-bordered">}}
|Operator|Description|Example|Result|
|--- |--- |--- |--- |
|+|addition|2 + 3|5|
|-|subtraction|2 - 3|-1|
|*|multiplication|2 * 3|6|
{{</table>}}
```
You can find more information at [https://www.monetdb.org/documentation/hugo-guide/elements/%23styled-tables](https://www.monetdb.org/documentation/hugo-guide/elements/%23styled-tables)
