### ISSUE TITLE
mclient aborted w/ FIPS 

### ISSUE THREAD

**Issue by ankravch** [MonetDB/MonetDB#7295]
**Describe the bug**
With FIPS enabled,  mclient throws error:
rmd_dgst.c(73): OpenSSL internal error, assertation failed: Digest RIPEMD160 forbidden in FIPS mode!
Aborted (core dumped)

**Software versions**
 - MonetDB 11.33.3 (Apr2019)
 - CentOS 7
 - self-installed and compiled
 - Libraries:
    openssl: OpenSSl 1.0.2k-fips 26 Jan 2017

**Comment by sjoerdmullender** [comment]
Apr2019 is no longer supported, but chances are that newer versions also wouldn't work for the same reason.
Since you're compiling it yourself, you can try disabling RIPEMD160 support.  You can edit the file `configure.ag` and remove the function `RIPEMD160_Update` from the list of functions that are inside a call to `AC_CHECK_FUNCS`.  Then rerun `bootstrap`, `configure`, etc.

**Comment by ankravch** [comment]
Thanks Sjoerd,  that worked.
