### ISSUE TITLE
can we use all the cores for parallel execution of a stand-alone python UDF 

### ISSUE THREAD

**Issue by SeverinaZheng** [MonetDB/MonetDB#7305]
When executing my python UDF in MonetDB on the 8-core machine, no matter using PYTHON or PYTHON_MAP, monetDB only use 1 or at most 2 cores at 100% and is super slow. The integers is just a dummy table for starting app(). The code is as follows:
DROP TABLE integers;
CREATE TABLE integers(i INTEGER);
INSERT INTO integers VALUES (1);
DROP FUNCTION app;
CREATE FUNCTION app() RETURNS STRING LANGUAGE PYTHON_MAP
{
//bootstrap my application which will keep running in the background
return 'OK'
};
SELECT app() from integers;
is there a way to parallelize app() to use all cores?
Thanks!

**Comment by SeverinaZheng** [comment]
When executing my python UDF in MonetDB on the 8-core machine, no matter using PYTHON or PYTHON_MAP, monetDB only use 1 or at most 2 cores at 100% and is super slow. The integers is just a dummy table for starting app(). The code is as follows:
DROP TABLE integers;
CREATE TABLE integers(i INTEGER);
INSERT INTO integers VALUES (1);
DROP FUNCTION app;
CREATE FUNCTION app() RETURNS STRING LANGUAGE PYTHON_MAP
{
  //bootstrap my application which will keep running in the background
  return 'OK'
};
SELECT app() from integers;
-------------------------------------------------
is there a way to parallelize app() to use all cores?
Thanks!

**Comment by aris-koning** [comment]
We don't offer parallel execution for 'foreign language' UDF's out of the box. You have to implement the parallelism yourself then in the body of the Python function in your case.

Next to the possibility that we can help you optimize your existing Python UDF, it would be an interesting challenge to extend our UDF framework to fit in our parallel execution paradigm. But this is out of the scope of community support and would require a turn-key project of some kind and perhaps **is not** the best way to go forward either.

Without knowing your Python code, we can at least give you a few hints about parallel processing in Python: first of all be aware that multi-threading in the standard implementation of Python (CPython I believe) is problematic because of the Global Interpreter Lock. So then you are probably better off if you would use the [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) module. Or you may want to switch to a different implementation of Python, e.g. IronPython that should provide better performance for multi-threaded applications.

Alternatively, you might consider writing your UDF in a different language that offers better threading implementations then CPython which performance-wise may lead you to consider using a combination of built-in and extended C functions to implement your UDF functionality.

If you need more help with any of this, I think it might be a good idea to consider commercial support.
