### ISSUE TITLE
ODBC SQLColums() issue with Alteryx

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7313]
**Describe the bug**
I cannot see the columns of a table in Alteryx. Alteryx uses an ODBC connexion to retrieve the information. On #6800 , Martin suggests that can be linked to SQLColums() function issue.
Here are the ODBC logs if that can help
[SQL.LOG](https://github.com/MonetDB/MonetDB/files/9027104/SQL.LOG)

**To Reproduce**
1/Create ODBC Connection to a monetdb database
2/Open Alteryx, use a data input box and connect to the odbc database configured in 1/

**Expected behavior**
-no error message in logs
-columns appeared in Alteryx

**Screenshots**
![image](https://user-images.githubusercontent.com/46959192/176848845-d2f38cc1-fabb-4d10-8279-bf9c0425508b.png)

**Software versions**
 - MonetDB version number : 11.43.9
 - odbc driver : 11.43.9.01
- OS and version: Windows 10
 - Installed from release package
 - Alteryx 2022.1

**Issue labeling **
ODBC driver

**Additional context**
For testing, you can download a version of Alteryx, there is a trial for a few days. Or just contact me, it would be a pleasure.

**Comment by mvdvm** [comment]
Thanks for sharing the ODBC.LOG trace information. This is needed in order to do the ODBC function call analysis.
From this log it shows that AlteryxGui aplication does NOT call the SQLColumns() function at all. Hence there is also no column information requested from the ODBC driver.
I did see it calls SQLTables() several times for different table types and schemas. This works okay. The data is retrieved using SQLGetData() and SQLFetch(). Those are also shown in the gui.

I did also see it sends a query:
  "select * from demo.exemplecomparetable.fruit1 a where 0=1"
This query fails with error: "SELECT: only a schema and table name expected", which is correct as MonetDB does not support catalog qualifiers before the schema name qualifier. Did it show this message also to the user?
The query should have been:
  "select * from exemplecomparetable.fruit1 a where 0=1"
in order to work correctly and return a result including the column names. Potentially this is how Alteryx finds out what the column names are for a specifc table, instead of using SQLColumns() function call.
Idem for tables fruit2 and fruit3.

Can you tell me if you entered this select query manually or was it generated by the AlteryxGui aplication?

Can you test if you can enter the query: 
  select * from exemplecomparetable.fruit1 a where 0=1;
and if it returns the column names (as header of an empty result table)?

**Comment by simonaubertbd** [comment]
Hello @mvdvm 

Very interesting analysis and thanks for taking the point.

_"This query fails with error: "SELECT: only a schema and table name expected", which is correct as MonetDB does not support catalog qualifiers before the schema name qualifier. Did it show this message also to the user?"_


It's not shown at all to the user, we juste have the screen shown without anything more.

_"Can you tell me if you entered this select query manually or was it generated by the AlteryxGui aplication?"_

It's generated by the AlteryxGui. The action I did was basically what we do to explore the database and retrieve the tables.

_Can you test if you can enter the query:
select * from exemplecomparetable.fruit1 a where 0=1;
and if it returns the column names (as header of an empty result table)?_

This way works fine but I have to guess or find another way to get the information (through dbeaver and friends)
![image](https://user-images.githubusercontent.com/46959192/177861000-e6bf3414-f315-4ba0-9281-783c127294ee.png)


Correct me if I'm wrong but what I understand is there are two issues
-Alteryx does not use the ODBC SQLColums() while it should. So I made this suggestion in their idea section : 
https://community.alteryx.com/t5/Alteryx-Designer-Ideas/Alteryx-should-use-ODBC-SQLColums-function-instead-of-sending-a/idi-p/965136#M17315
-MonetDB does not accept 3-level column name. I didn't find an issue about that so I will create one in a few days.

Best regards,

Simon

**Comment by mvdvm** [comment]
Hi Simon,

Normally if an ODBC application needs to know the column information of a specific table or view it would use SQLColumns(). However that is not required. The way Alteryx does it is also possible, but may be slower than using the SQLColumns().

You do not need to log an issue for the 3-level table name qualifier error (so: catalog.schema.table) because we are not going to support it.
Instead I think the MonetDB ODBC driver currently may be wrong in returning data for the catalog info, while we do not support catalog qualifiers. So I am going to correct that. Hopefully when that is implemented AlteryxGui will no longer use a catalog prefix when constructing SQL queries.

Martin

**Comment by mvdvm** [comment]
Hi Simon,

I have discussed this issue internally and we think the Alteryx ODBC application is missing an important ODBC SQLGetInfo() call in order to determine whether catalog names are supported by a driver or not and catalog name qualifier should be used in a SQL statement.
According to the ODBC specification an ODBC application should call:  SQLGetInfo(hdbc, SQL_CATALOG_NAME, ...) to determine whether catalogs are supported by a driver or not.
See https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetinfo-function
For SQLGetInfo(hdbc, SQL_CATALOG_NAME, ...) the MonetDB ODBC driver correctly returns "N" meaning the driver does NOT support catalog names.
Other related SQLGetInfo() calls also consistently return information that the MonetDB ODBC driver does NOT support catalog names:
 SQLGetInfo(hdbc, SQL_CATALOG_LOCATION, ...)  returns 0 meaning no support for catalog names
 SQLGetInfo(hdbc, SQL_CATALOG_NAME_SEPARATOR, ...)  returns empty string meaning no support for catalog names
 SQLGetInfo(hdbc, SQL_CATALOG_TERM, ...)  returns empty string meaning no support for catalog names
 SQLGetInfo(hdbc, SQL_CATALOG_USAGE, ...)  returns 0 meaning no support for catalog names in any SQL query or DDL statement.

I checked the ODBC SQL.LOG file you provided and did not see these specific calls been done by Alteryx ODBC application.
Hence we think the Alteryx ODBC application is not properly using the ODBC API as it is designed and specified.
We suggest to log this problem with Alteryx so they can correct/improve their application such that for the MonetDB ODBC driver it no longer creates queries with a catalog qualifier such as: "select * from demo.exemplecomparetable.fruit1 a where 0=1".
Once that is corrected by Alteryx you should see the columns of a table in your GUI as expected.

Regards,
Martin

**Comment by simonaubertbd** [comment]
Hello @mvdvm,

Thanks for the very clear explanations, I will have to discuss with Alteryx. I know they use a third-party software on this part (Active Query Builder https://www.activequerybuilder.com/product.html ) but don't know it they have the hand on the ODBC call or query. I have already asked for an update of this component.
I have seen on https://www.monetdb.org/hg/MonetDB/rev/5ffdacc0c593 you already made some update :) Thanks for that. Will it be packaged with the next release?

Best regards,

Simon

**Comment by mvdvm** [comment]
_Will it be packaged with the next release?_
Yes.
If you like you can already download and install the patched ODBC driver from: http://monetdb.cwi.nl/testweb/web/86079:7ecafb238d3b/ 
Note this is **an unreleased version, so only usable for testing**.
Let us know if this ODBC patch makes a difference with Alteryx. If possible, also provide a new ODBC trace log file. It is needed to find out what ODBC driver function calls are done by the Alteryx application.

**Comment by simonaubertbd** [comment]
Hello,

I updated my odbc driver in 11.44.00.01. Still have the same issue with the Visual Query Builder component.

Here are the logs.
[SQL.LOG](https://github.com/MonetDB/MonetDB/files/9121162/SQL.LOG)


On the other hand, with the Input Data Tool, this is also the same. But at least, the message is clear : Error: Input Data (4): Error SQLPrepare: [MonetDB][ODBC Driver 11.44.0]SELECT: only a schema and table name expected

![image](https://user-images.githubusercontent.com/46959192/179233453-6c39a078-e4a4-43f6-8bd8-63634bc5a845.png)

[SQL.LOG](https://github.com/MonetDB/MonetDB/files/9121180/SQL.LOG)

If I change manually the query by deleting the database (like the new message says ;)  ), it's fine : 
![image](https://user-images.githubusercontent.com/46959192/179234206-9dcd11d7-d1a8-46c7-bc20-6707f4dad6be.png)


Well, I will try to use that to convince Alteryx to change their logic.

Thanks for your prompt development.

**Comment by mvdvm** [comment]
Hi Simon,

I have made some more improvements to the MonetDB ODBC driver.
You can download the patched ODBC driver from: http://monetdb.cwi.nl/testweb/web/86184:9ace5c9b1de1/
Please first uninstall the previous installed ODBC driver 11.44.00.01 else the upgrade doesn't work as this new one also has version 11.44.00.01.
Note this is also an unreleased version, so only usable for testing **not for production.**
Let us know if this ODBC patch version makes a difference with Alteryx. If possible, also provide a new ODBC trace log file, so I can do more analysis.
I also fixed issue #7314 in this patched version, so you can also test that.

Thanks,
Martin

**Comment by simonaubertbd** [comment]
Hello @mvdvm  Thanks for your efforts. Sadly, it's worse now :
![image](https://user-images.githubusercontent.com/46959192/181780847-c9b283bd-3740-44e8-91be-e64841e869e8.png)
[SQL.LOG](https://github.com/MonetDB/MonetDB/files/9220743/SQL.LOG)

Best regards,

Simon

**Comment by simonaubertbd** [comment]
Also with Tableau 

through generic odbc 
![image](https://user-images.githubusercontent.com/46959192/181782598-2a0fb055-0ab0-4cb4-b9f1-c81eb6d133e7.png)

through monetdb entry 
![image](https://user-images.githubusercontent.com/46959192/181782822-027c2a5d-a8da-41ca-8f8c-9ad71b681528.png)

**Comment by mvdvm** [comment]
Thanks for testing. This behavior is unexpected. In the log file I see SQLSetConnectAttrW(SQL_ATTR_LOGIN_TIMEOUT, 15) being called with returning SQL_SUCCESS. This should have been SQL_SUCCESS_WITH_INFO, so something is not right here. Maybe the installation is not gone correctly. Can you call the installer again and choose the Repair button, so all the files are checked and possibly replaced again. Next turn on ODBC trace and test with Alteryx again.
If that gives the same connection error, uninstall the driver, next install the previous patch driver (from 15 july) and check the connection is working again.
Thanks

**Comment by simonaubertbd** [comment]
Hello @mvdvm 

Well, I shouldn't test and be covid-tired in the same time. For a reason I don't get, it's simply the monetdb server was off and I should have trust the message box :( . I apologize for that.


So the results : 
![image](https://user-images.githubusercontent.com/46959192/181879038-6b769621-5fe6-4ddc-8bad-d406fc79ebff.png)

[SQL.LOG](https://github.com/MonetDB/MonetDB/files/9225527/SQL.LOG)


Best regards,

Simon

**Comment by mvdvm** [comment]
I have analysed your latest SQL.LOG file.
It shows that at line 3589 it calls SQLTables() and next fetches all 41 tables found (lines 4547 till 8166). This includes 38 MonetDB system tables and your 3 user tables: "fruit1", "fruit2" and "fruit3" in schema: "exemplecomparetable".
It is AlteryxGui code which should have displayed this information, but somehow it doesn't. This is not a bug in the ODBC driver, but in the AlteryxGui program, as the data is clearly retrieved and passed on.
Next it calls SQLGetConnectAttrW(hdbc, SQL_ATTR_CURRENT_CATALOG, ...) 4 times! All return SQL_SUCCESS with an empty string as catalog name, as MonetDB has no catalog qualifiers.
Apparently the AlteryxGui program expects/requires a non empty CATALOG value, but that is a wrong assumption.

I can not find any problems with the MonetDB ODBC driver. It is the AlteryxGui application which is wrong in how it uses the ODBC API as mentioned before. It should not require every ODBC Data Source to support catalog names.

Could you also test Tableau with this latest patched driver version? I would like to know if this works okay as these improvements will become part of the next release. If possible make a SQL.LOG again.
Merci.

**Comment by simonaubertbd** [comment]
Hello @mvdvm . Thanks a lot for the analysis. There is a huge room to improve Alteryx interoperability, I guess.

Here the result with Tableau. No trouble with it. 
[SQL.LOG](https://github.com/MonetDB/MonetDB/files/9253472/SQL.LOG)

Best regards,

Simon
