### ISSUE TITLE
INTERVAL SECOND columns become incorrect when an INTERVAL HOUR column is present

### ISSUE THREAD

**Issue by joerivanruth** [MonetDB/MonetDB#7353]
Consider the following query
```
SELECT
    value AS v,
    CAST(CAST(value AS TEXT) AS INTERVAL HOUR)    AS h,
    CAST(CAST(value AS TEXT) AS INTERVAL SECOND)  AS s
FROM sys.generate_series(1, 2);
```
I would expect the following result:
```
+------+----------+-------+
| v    | h        | s     |
+======+==========+=======+
|    1 | 3600.000 | 1.000 |
+------+----------+-------+
```
But I get
```
+------+----------+----------+
| v    | h        | s        |
+======+==========+==========+
|    1 | 3600.000 | 3600.000 |
+------+----------+----------+
```
As you can see the 3600.000 gets duplicated from the h column to the s column.
Looking in the EXPLAIN output I notice
```
    X_12:bat[:lng] := batcalc.second_interval(X_10:bat[:str], nil:BAT, 8:int, 0:int);
. . .
    X_15:int := sql.resultSet( . . ., X_9:bat[:bte], X_12:bat[:lng], X_12:bat[:lng]);
                                                     ^^^^            ^^^^
```
The result of a single batcalc.second_interval() call gets reused for both columns. I quickly checked opt_CommonTerms.c but at first glance the damage already seemed to be done by the time we got there. 

**Software versions**
MonetDB commit c56826b78db5d53b36ea62d4c0d6f11dcecbc9e9 on the Sep2022 branch. Running under Debian11 (bullseye).

**Comment by sjoerdmullender** [comment]
The problem seems to be in `subtype_cmp` which is called to check whether the conversions to the interval types are the same during the `rel_optimize_projections` optimization phase.  It returns that they are, despite the subtypes (as indicated by the `digits` value) being different.
This is the relevant code
```
	if (t1->type->eclass == t2->type->eclass && t1->type->eclass == EC_SEC)
		return 0;
```
0 meaning equal.
If I change that return to `return -(t1->digits != t2->digits);` (0 if equal, -1 if not) the two don't get collapsed to one and the result is as expected.  However, a lot of other tests fail with this change, so I am not going to push this fix.

**Comment by njnes** [comment]
on aug2024 I get the expected result.

**Comment by njnes** [comment]
fixed in aug2024
