### ISSUE TITLE
GDKextendf: CRITICAL: could not extend file: File too large

### ISSUE THREAD

**Issue by lampt-uit** [MonetDB/MonetDB#7396]
**Describe the bug**
When I execute a complex query,  this error appears.

**Screenshots**
![Screenshot 2023-07-26 at 23 13 21](https://github.com/MonetDB/MonetDB/assets/73767803/58b67cdd-bd2f-4740-bab9-dfaec27c3823)

**Software versions**
 - MonetDB Database Server Toolkit v11.47.3 (Jun2023)
 - OS and version: Ubuntu 20.04.5 LTS (Focal Fossa)
 - Installed from compiled

**Comment by sjoerdmullender** [comment]
Looks like your query gets translated to something that does a crossproduct, and that crossproduct is way too large.  In other words, the query is not going to work.
You may have to change the query so that the translator can avoid the crossproduct, or if you're really requesting a crossproduct, that is not going to work.
In order to get help with the query, we need to know the schema, the query, and at least some sizes of the tables involved.
