### ISSUE TITLE
Maybe we don't need 32 bits anymore?

### ISSUE THREAD

**Issue by simonaubertbd** [MonetDB/MonetDB#7423]
**Is your feature request related to a problem? Please describe.**
Not a problem for me but I guess developers struggle with a lot of versions... and who use MonetDB on a windows 32 bits today?

**Describe the solution you'd like**
to stop 32 bits editions of MonetDB

**Describe alternatives you've considered**
None

**Additional context**
Windows 11 only comes in 64 bits

**Comment by mvdvm** [comment]
Some people still use them ;))
Also the 32-bit ODBC driver still needs to be available for older 32-bit ODBC applications running on 64 bit OS.
So that still needs to be compiled and released.

We also use the Windows 32-bit version to test MonetDB server on a limited OS (Max 3 GB RAM and 1.5GB Virtual memory) in our nightly regression test web.  This allows us to detect scalability problems early on during development and changes to algorithms and optimizers as they would cause a fatal "could not extend virtual memory" error.

**Comment by simonaubertbd** [comment]
Hello @mvdvm  Ok, no trouble, I hoped to save the team some time but I get it.  ^^
