### ISSUE TITLE
Performance issue in select-joins

### ISSUE THREAD

**Issue by swingbit** [MonetDB/MonetDB#7424]
**Describe the bug**
Select-join (N x 1) resorts to full scan-select instead of creating a hash table. Since this join uses `BATselect()`, I expect the same issue to be related to point selections.
 
**To Reproduce**
```sql
set optimizer='sequential_pipe';
start transaction;

-- t contains unique strings (scale up the size as desired)
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
alter table t add unique(u);
analyze sys.t;

-- s contains one value value from t
create table s as select * from t sample 1;

trace select * from t, s where t.u = s.u;
```
The trace shows that a full scan is performed:
```
| 10688 |     (X_16=[1]:bat[:oid], X_17=[1]:bat[:oid]) := algebra.join(X_14=[1000000]:bat[:str], X_15=[1]:bat[:str], nil:BAT, nil:BAT, false:bit, nil:lng); # selectjoin; select: fullscan equi |
```
If you scale up the size of the table to a couple of hundred million tuples, this scan costs about 5 seconds, while the join could be answered in tens of milliseconds with a hash on the large table.

Note that the column is marked unique and the table analyzed. Especially in this case I'd expect a hash table. How is uniqueness implemented if not with a hash table? Is it created and then destroyed? That would be a waste.

**Expected behavior**
I'd expect a hash to be created on the large table. 

**Software versions**
 - MonetDB version number v11.47.18
 - OS and version: Fedora 39
 - self-installed and compiled

**Comment by njnes** [comment]
did you try without the initial 'start transaction'?

**Comment by swingbit** [comment]
Interesting.. removing `start transaction;` takes only 14us , which probably means it did reuse an available hash.

```
|   14 |     (X_23=[1]:bat[:oid], X_24=[1]:bat[:oid]) := algebra.join(X_21=[1000000]:bat[:str], X_22=[1]:bat[:str], nil:BAT, nil:BAT, false:bit, nil:lng); # selectjoin; hashselect   |
```

Should it be able to use it also within  an open transaction or is there some good reason why it can't?

**Comment by sjoerdmullender** [comment]
It could, but it won't.  There is no hash as yet since the bats involved are not persistent (due to the START TRANSACTION).  So any created hash will be destroyed again, giving no benefits for future queries, so there is no point in creating an expensive one.  We do estimate what is the cheapest option to do the join, and this estimate takes into account hash creation on transient bats.  If the bat were persistent, we assume that the hash will be reused, so we don't mind creating one.

**Comment by swingbit** [comment]
Of course, my bad. I started from something I observed in a real application and then tested with that little example, but that should have been:

```sql
set optimizer='sequential_pipe';

drop table if exists t;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);

alter table t set read only;
alter table t add unique(u);
analyze sys.t;

start transaction;

create table s as select * from t sample 1;
trace select * from t,s where t.u=s.u;
```

which does indeed reuse the existing hash.

That means I still need to find a script to reproduce the problem I observed.

**Comment by swingbit** [comment]
@sjoerdmullender @njnes , what about this? I think it is more similar to my use case:

```sql
START TRANSACTION;
  drop table if exists t;

  create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
  alter table t set read only;
  alter table t add unique(u);
  analyze sys.t;
COMMIT;

START TRANSACTION;
  create table s as select * from t sample 1;
  trace select * from t,s where t.u=s.u;
ROLLBACK;
```

Now table `t` is persistent, but no hashjoin:
```
| 22961 |     (X_16=[1]:bat[:oid], X_17=[1]:bat[:oid]) := algebra.join(X_14=[1000000]:bat[:str], X_15=[1]:bat[:str], nil:BAT, nil:BAT, false:bit, nil:lng); # selectjoin; select: fullscan equi |
```

Why is several individual transactions for creating and altering `t` any different from one single transaction for that?

(I also tried taking the `DROP TABLE` outside the first transaction, it does not change the result )

**Comment by swingbit** [comment]
Another way to put it:

I always thought that a statement in auto-commit mode is equivalent to
```sql
START TRANSACTION;
<statement>
COMMIT;
```

but this is not the case.

If I use this in auto-commit mode:
```sql
  create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
  alter table t set read only;
  alter table t add unique(u);
  analyze sys.t;
```

then I do get a hash-join.

But if I wrap each single statement in a separate explicit transaction (which I thought to be equivalent), then I do not get a hash-join.

**Comment by sjoerdmullender** [comment]
Because one side of the join is a single value, the join implementation uses select to perform the join.  Select doesn't always create a hash because that is too costly.  However, if you select often enough on the same bat, select will create a hash.  So, if you repeat this join 1000 times, it will all of a sudden become a lot faster.

**Comment by swingbit** [comment]
@sjoerdmullender ok, I see that. I'm not sure I completely agree with the logic in `BATselect()` (although I agree that it's difficult to find the sweet spot between opposite optimization choices), because I'd much rather have 1 very slow select than having 1000 slow selects.

But that is about having `BATselect()` creating the hash. What I wonder now is instead why it doesn't find an existing one. 

Creating the large table in auto-commit mode does create a hash that is immediately found by the first select-join attempt.

Why is that not the same when the large table is created within an explicit committed transaction?

**Comment by sjoerdmullender** [comment]
When you do the ANALYZE query inside the START TRANSACTION/COMMIT, the bats are not yet persistent, so if a hash is created, it is also discarded.  If you were to repeat the ANALYZE after the COMMIT, no hash is created since the knowlegde is already there.
If you run in autocommit mode, by the time you call ANALYZE, the bats have already been made persistent, so the hash that ANALYZE creates in order to find out the uniqueness is kept.
As mentioned before, the join/select doesn't necessarily create a hash, but it will use one if it's there.

**Comment by swingbit** [comment]
Thanks, that clears part of the issue for me. 

The `ANALYZE` argument makes sense, and although having to get rid of the wrapping transaction is very application-unfriendly, I'm willing to change how these statements are executed, but I'm not even sure the auto-commit mode would work the same way via JDBC.

From what I've seen so far, the only way is to execute these in auto-commit mode:
```sql
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
alter table t add unique(u);
analyze sys.t;
```

However, I still don't get how that is not equivalent to:
```sql
START TRANSACTION;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
COMMIT;
START TRANSACTION;
alter table t add unique(u);
COMMIT;
START TRANSACTION;
analyze sys.t;
COMMIT;
```
Here, the `ANALYZE` does work on a persisted bat. Still, no hash is kept.

**Comment by sjoerdmullender** [comment]
When I try these queries and then the join, I see `# selectjoin; hashselect` in the trace.  This uses a hash.

**Comment by swingbit** [comment]
Oh! Using the separate transactions I also do get the hashselect on Jun2023.
But I don't get it on Dec2023. Do you?

**Comment by sjoerdmullender** [comment]
I was using Dec2023.

**Comment by swingbit** [comment]
Hold on. It's not about Jun2023 or Dec2023.

I get the hash-join only the first time I execute the script. After that, even stopping/starting the database does not get me a hash-join, until I recreate the db.

This is the script I use, please try it on a new database and then again:
```sql
set optimizer='sequential_pipe';

drop table if exists t;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);

START TRANSACTION;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
alter table t add unique(u);
COMMIT;

START TRANSACTION;
analyze sys.t;
COMMIT;

start transaction;
create table s as select * from t sample 1;
trace select * from t,s where t.u=s.u;
rollback;
```

**Comment by swingbit** [comment]
Did I mess up my scripts while testing? You're right...

This does work:
```sql
START TRANSACTION;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
alter table t add unique(u);
COMMIT;

START TRANSACTION;
analyze sys.t;
COMMIT;
```
Sorry about that confusion.


I do understand your argument of the analyze not working on a non-persistent bat, although that really isn't very nice to use.

Could you only just clarify for me why in the following the hash that is created by the unique constraint isn't kept though?
```sql
START TRANSACTION;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
alter table t add unique(u);
analyze sys.t;
COMMIT;
```

I don't mean for the analyze. I mean for the join, later. The transaction is committed, so why discard that hash?

**Comment by sjoerdmullender** [comment]
The analyze query calls BATunique to find out the uniqueness state of the bat.  BATunique will create a full hash _if the bat is persistent_.  But the bat is not (yet) persistent, so BATunique instead creates a partial hash where only distinct values are kept.  Since it's only a partial hash, it is destroyed at the end.

**Comment by swingbit** [comment]
oh ok, I thought the unique constraint was the one creating the hash.

**Comment by sjoerdmullender** [comment]
You can see the difference if you trace the anaylize.
Inside the transaction:
`X_9=0@0:void := sql.analyze("sys":str, "t":str); # unique: new partial hash`
Outside the transaction:
`X_9=0@0:void := sql.analyze("sys":str, "t":str); # create hash; unique: existing hash`

**Comment by sjoerdmullender** [comment]
The ALTER query is inside the transacion, so the bats are still transient.  The implementation uses a BATgroup which creates a temporary partial hash to do the work, so this is discarded.
The biggest problem I see here is that the knowledge that the colum is unique is not recorded in the bat, so the analyze needs to do more work.  On the other hand, because of that, you get a hash if you call the analyze outside of the transaction.
I'm not sure whether the BATgroup would create a more permanent hash if done on a persistent bat.

**Comment by swingbit** [comment]
Ah, I see. The unique constraint also only creates a partial one, that is why it's not kept after the commit.

In fact, if I first analyze, creating a full one, then the unique constraint just uses that one.

That is, if they all run in separate transactions.

OK, now I understand,thanks for explaining.
I have to say it's a bit tricky, because for an application point of view you want a set of operations to behave atomically, hence you group them in one transaction, but then you don't get what you'd expect.

**Comment by swingbit** [comment]
Perhaps one thing that still feels wrong is this.

```sql
set optimizer='sequential_pipe';

drop table if exists t;

START TRANSACTION;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
alter table t add unique(u);
--analyze sys.t;
COMMIT;

START TRANSACTION;
analyze sys.t;
COMMIT;

start transaction;
create table s as select * from t sample 1;
trace select * from t,s where t.u=s.u;
rollback;
```

This works as expected.

However, enabling the analyze that is now commented (without removing the one outside) makes the hashjoin disappear again. 

I find this illogical. The analyze inside the transaction will not find a persistent bat, hence no full hash. But the one outside the transaction should still do it.

**Comment by sjoerdmullender** [comment]
The analyze tries to determine whether the values in the columen are all distinct and records the result as a bat property.  The second time you run it, the analyze has nothing to do since the question has already been answered.

**Comment by swingbit** [comment]
:) ok .. I mean, I understand the explanation, but that feels so much like a trap..

**Comment by sjoerdmullender** [comment]
There is another factor that plays into all of this.
As long as the WAL has not yet been flushed, all bats are actually still transient.  A server restart after table creation and before any querying would resolve that.  Also, as of the Dec2023 version, waiting for about 10 minutes will also do that.  I understand, neither is very satisfactory.

**Comment by swingbit** [comment]
At the end of the day, all I wanted was to make sure that a hash is available on a persistent column, in order to answer point queries fast  - but I can't do that explicitly.

MonetDB decides itself when to create indices, which is great, but if one wants to make sure the index is there, much juggling with transactions seems to be necessary, and transaction logic that is not natural for the application.

Am I missing a simple way to make sure that hash is available?

**Comment by sjoerdmullender** [comment]
If you make sure all the relevant tables (bats) have been made persistent (i.e. the WAL has been processed), things are a lot easier since we are more willing to create hashes.  But even then there is currently no guarantee.

But I think what we need to do is to instead of looking at whether the bat is _currently_ persistent, look at what the "role" is of the bat, i.e. is it likely to _become_ persistent?  Also, the BATselect code should create a hash for persistent bats (also when only the role is persistent) when doing a point select, and not just after 1000 times.

**Comment by swingbit** [comment]
Yeah, I like that line of thought. 

Even with the original script:
```sql
START TRANSACTION;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
alter table t add unique(u);
analyze sys.t;
COMMIT;
```

It's true that the `t` isn't persistent at the time of `analyze`, but the whole committed transaction clearly indicates that `t` is there to stay and be used. Not only the following queries would benefit from that, but also the unique constraint and the analyze would help each other, because they would both use the same hash.

**Comment by sjoerdmullender** [comment]
The alter query calls BATgroup which is presented (in this case) with a view of the base table column (if there were NULLs, it wouldn't be a view).  There is disabled code in there to use (and possibly create) a hash on the parent bat (i.e. the base table bat).  I do not want to reeanble that code now.  The reason it was disabled is that a BATgroup on a view can be done in parallel to another query modifying (appending to) the column.  Without a lot more precautions, this would mess up the grouping code.  I know, in this case, since the base table was created in the same SQL transaction, this scenario cannot happen, but the grouping code doesn't know that.  For the same reason, the knowledge that BATgroup gained about uniqueness is not propagated to the parent bat, although this might be possible--I need to look into that.  So, it is unlikey that the alter will any time soon create a persistent hash.
The BATunique call that is done by the analyze query faces a similar problem.  There too, the uniquness information could probably be passed on to the parent bat in certain cases, but that doesn't happen currently.

**Comment by swingbit** [comment]
I tried [your commit ](4a561014ce643f3671c729da6d1679dd0ff64af3), it does trigger the creation of the hash on the first select join.

For curiosity, I also tried it on this smaller example (no unique constraint and no analyze):
```sql
START TRANSACTION;
create table t as select cast(uuid() as string) as u from generate_series(0,1000000);
COMMIT;

start transaction;
create table s as select * from t sample 1;
trace select * from t,s where t.u=s.u;
rollback;
```
I'm just curious about the 3 `select: fullscan equi` before `create hash; hashselect`:

```
| 154375 |     (X_20=[1]:bat[:oid], X_21=[1]:bat[:oid]) := algebra.join(X_18=[1000000]:bat[:str], X_19=[1]:bat[:str], nil:BAT, nil:BAT, false:bit, nil:lng); # selectjoin; select: fullscan equi; select: fullscan equi; select: fullscan equi; create hash; |
:        :  hashselect                                                                                                                                                                                                                                       :
```
They are not there if I also include the analyze.

**Comment by sjoerdmullender** [comment]
That's three selects on small slices of the bat in order to estimate the result size.
