### ISSUE TITLE
[bug] the table cannot be created because the reserved word is incorrectly set

### ISSUE THREAD

**Issue by Nliver** [MonetDB/MonetDB#7444]
**Describe the bug**
the table cannot be created because the reserved word is incorrectly set
![image](https://github.com/MonetDB/MonetDB/assets/34496563/ce75394e-98be-4650-b97f-ffb4e7f2b536)
![image](https://github.com/MonetDB/MonetDB/assets/34496563/2a21ae2d-7426-416c-b469-5a0551f5e925)

**Software versions**
 - MonetDB version number：Jun2023 Feature Release (11.47.3)
 - OS and version: Ubuntu 20.06
 - self-installed and compiled

**Comment by mvdvm** [comment]
The SQL parser currently treats `greatest` as a special keyword, because it is also a built-in function name.
We need to further investigate if it should be accepted or treated as a reserved keyword.
This also applies to `least`.

As a workaround you can enclose the column name with double quotes i.e.: 
`create table ttt("greatest" int);`
`select "greatest" from ttt;`

**Comment by njnes** [comment]
pushed a fix to the dec2023 branch
